@SubManager_HostAddress = http://localhost:5165

GET {{SubManager_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{SubManager_HostAddress}}/videos/duration-status?ids=1&ids=2
Accept: application/json

###
