<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>6b358fa7-83f5-4208-a84c-2687cbbecabc</UserSecretsId>
      <RootNamespace>SubManagerLite</RootNamespace>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FlexLabs.EntityFrameworkCore.Upsert" Version="10.0.0" />
        <PackageReference Include="Gridify.EntityFramework" Version="2.19.1" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.8" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
        <PackageReference Include="YoutubeExplode" Version="6.5.7" />
    </ItemGroup>

</Project>
