services:
  submanager:
    image: submanager:local
    build:
      context: .
      dockerfile: Dockerfile

  migrate:
    image: submanager:local
    build:
      context: .
      dockerfile: Dockerfile
